# Generated by Django 4.2.6 on 2023-12-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('trip_title', models.CharField(max_length=100)),
                ('trip_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('age_limit', models.IntegerField()),
                ('best_weather', models.TextField(choices=[('summer', 'summer'), ('winter', 'winter'), ('spring', 'spring'), ('autumn', 'autumn')])),
                ('is_open', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='categories.category')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
