# Generated by Django 4.2.6 on 2023-12-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_rating',
        ),
    ]
