# Generated by Django 4.2.6 on 2023-12-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_trip_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedTrip',
            fields=[
                ('trip_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trips.trip')),
                ('admin_approved', models.BooleanField(default=False)),
            ],
            bases=('trips.trip',),
        ),
    ]
