# Generated by Django 4.2.6 on 2023-12-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_requestedtrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='location_id',
            new_name='location_name',
        ),
    ]
