# Generated by Django 4.2.6 on 2023-12-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_rename_location_id_trip_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='location_name',
            new_name='location_id',
        ),
    ]
