# Generated by Django 4.2.6 on 2023-12-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_location_name_trip_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='location_id',
            new_name='location',
        ),
    ]
