# Generated by Django 4.2.6 on 2023-10-13 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('attack_priority', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('enemy_organization', models.TextField(max_length=100)),
                ('target_goal', models.TextField(max_length=100)),
                ('was_target_destroyed', models.BooleanField()),
                ('target_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
