# Generated by Django 4.2.6 on 2023-12-13 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_published',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
    ]
