version: "3.8"

services:
  app3:
    image: app3:1
    container_name: app3
    ports:
      - "3000:3000" 


  mongo:
    image: mongo:latest
    container_name: mongodb
    ports: 
    - "27017:27017"
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db


volumes:
  MONGO_DATA:
    name: MONGO_DATA