version: '3'

services:
  script:
    build: .
    restart: always
    container_name: script
    ports:
      - "5001:5001"
    env_file:
      .env
    depends_on:
    - mysql

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    env_file:
      .env
    ports:
      - "3306:3306"