apiVersion: v1
kind: Service
metadata:
 name: frontend-service
 namespace: my-first-namespace
 labels:
   app: frontend-app
spec:
 type: NodePort
 selector:     
   app: frontend-app
 ports:
   - protocol: TCP
     port: 32499
     targetPort: 8000