# Generated by Django 4.2.6 on 2023-10-24 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.core.validators.MinValueValidator(0))),
                ('email', models.EmailField(max_length=254)),
                ('unread_messages', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
