# Generated by Django 4.2.6 on 2023-10-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_message_read'),
        ('users', '0002_alter_user_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message'),
        ),
    ]
