# Generated by Django 4.2.6 on 2023-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_message_read'),
        ('users', '0005_alter_user_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unread_messages',
        ),
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, to='message.message'),
        ),
    ]
