# Generated by Django 4.2.6 on 2023-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_unread_messages_user_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
