# Generated by Django 4.2.6 on 2023-12-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('role', models.TextField(choices=[('user', 'user'), ('admin', 'admin')])),
            ],
        ),
    ]
