# Generated by Django 4.2.6 on 2023-10-24 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.core.validators.MinValueValidator(0))),
            ],
        ),
    ]
