# Generated by Django 4.2.6 on 2023-10-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('event_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('waiting for response', 'Waiting for response'), ('waiting for handling', 'Waiting for handling')], max_length=100)),
                ('can_draft', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_users', to='users.user')),
                ('user_reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='SharedForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.form')),
                ('uploading_date', models.DateField()),
                ('file', models.FileField(upload_to='forms/')),
                ('uploading_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            bases=('forms.form',),
        ),
        migrations.CreateModel(
            name='MessagesForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forms.form')),
                ('message_history', models.JSONField()),
                ('chat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chat')),
            ],
            bases=('forms.form',),
        ),
    ]
