# Generated by Django 4.2.6 on 2023-10-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploading_date', models.DateField()),
                ('file', models.FileField(upload_to='')),
                ('uploading_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('event_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Waiting for Response', 'Waiting for Response'), ('Waiting for Handling', 'Waiting for Handling')], max_length=20)),
                ('can_draft', models.BooleanField()),
                ('can_download', models.BooleanField()),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_events', to='users.user')),
                ('user_reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
