# Generated by Django 4.2.6 on 2023-10-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_sharedform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedform',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
