# Generated by Django 4.2.6 on 2023-10-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_sharedform_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesform',
            name='message_history',
        ),
    ]
