# Generated by Django 4.2.6 on 2023-10-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_messagesform_receiver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesform',
            old_name='receiver_user',
            new_name='receiver_users',
        ),
    ]
