# Generated by Django 4.2.6 on 2023-10-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_unread_messages_user_unread_messages'),
        ('message', '0002_message_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='users.user'),
            preserve_default=False,
        ),
    ]
