# Generated by Django 4.2.6 on 2023-10-15 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('person_id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.core.validators.MinValueValidator(0))),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.TextField(max_length=100)),
            ],
        ),
    ]
