# Generated by Django 4.2.6 on 2023-10-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='work_place',
        ),
    ]
