# Generated by Django 4.2.6 on 2023-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_remove_parent_basic_salary_remove_parent_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(blank=True, related_name='parents', to='people.person'),
        ),
        migrations.AddField(
            model_name='parent',
            name='work_place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
