# Generated by Django 4.2.6 on 2023-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_parent_basic_salary_parent_kids_parent_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='basic_salary',
            field=models.IntegerField(default=0),
        ),
    ]
