# Generated by Django 4.2.6 on 2023-10-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_parent_basic_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='basic_salary',
            new_name='baseSalary',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='kids',
            new_name='children',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='work_place',
            new_name='work',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='date_of_birth',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='homeTown',
        ),
    ]
