# Generated by Django 4.2.6 on 2023-10-22 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_parent_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='basic_salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
