# Generated by Django 4.2.6 on 2024-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('seniority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
